export const siteConfig = {
  accentColor: "#1d4ed8",
  en: {
    name: "Amine Sadali",
    title:
      "Senior Technical Consultant & Full-Stack Developer",
    description:
      "Senior Technical Consultant and Full-Stack Developer specializing in React, Node.js, and cloud-native, AI-integrated enterprise applications.",
    social: {
      email: "amine.sadali@gmail.com",
      linkedin: "https://www.linkedin.com/in/aminesadali",
      twitter: "",
      github: "https://github.com/Z4D4LY",
    },
    contact: {
      phone: "0632400390",
      location: "Casablanca",
      nationality: "Moroccan",
      remote: "Open to remote & hybrid work",
    },
    profile:
      "Senior Technical Consultant and Full-Stack Developer with 5+ years of experience designing and developing scalable web applications, microservices, and enterprise middleware. Expertise in React, Node.js, TypeScript, cloud-native architectures, and AI-integrated solutions.",
    interests: ["Artificial Intelligence", "Open Source", "Cloud", "Information Systems"],
    cvSkills: {
      frontend: [
        "React.js",
        "Next.js",
        "Redux.js",
        "Tailwind CSS",
        "SASS",
        "HTML",
        "CSS",
        "Webpack",
        "Figma",
        "WordPress",
        "Shopify",
        "Strapi",
      ],
      backend: [
        "Node.js",
        "NestJS",
        "Express",
        "Python",
        "TypeScript",
        "JavaScript",
        "Microservices",
        "REST APIs",
        "MERN Stack",
        "Stripe",
        "MongoDB",
        "MySQL",
        "Oracle Database",
        "Microsoft SQL Server",
        "PL/SQL",
        "Firebase",
      ],
      devops: [
        "DevOps",
        "Docker",
        "Kubernetes",
        "CI/CD",
        "SonarQube",
        "Microsoft Azure",
        "Cloud Computing",
        "Git",
        "GitLab",
        "Bash",
        "Unix",
        "SaaS/PaaS/IaaS",
        "Project Management",
      ],
      aiMl: [
        "Agentic AI Development",
        "Retrieval-Augmented Generation (RAG)",
        "Large Language Models (LLM)",
        "Prompt Engineering",
        "LangChain",
      ],
    },
    aboutMe:
      "Consulting, Architecture & Application Development. Proven track record across both permanent (CDI) and freelance roles, architecting and building scalable enterprise applications. Deep expertise in the JavaScript/TypeScript ecosystem, with hands-on work as a core developer of the eas'eFlow / eas'Invoice enterprise middleware suite. End-to-end DevOps and infrastructure control and automation. I deliver AI-integrated, high-performance solutions for global clients, and I'm open to strategic partnerships and technical collaborations.",
    skills: [
      "Agentic AI Development",
      "Retrieval-Augmented Generation (RAG)",
      "Large Language Models (LLM)",
      "Prompt Engineering",
      "LangChain",
      "Node.js",
      "NestJS",
      "Express",
      "Python",
      "TypeScript",
      "JavaScript",
      "Microservices",
      "REST APIs",
      "MERN Stack",
      "Stripe",
      "MongoDB",
      "MySQL",
      "Oracle Database",
      "Microsoft SQL Server",
      "PL/SQL",
      "Firebase",
      "DevOps",
      "Docker",
      "Kubernetes",
      "CI/CD",
      "SonarQube",
      "Microsoft Azure",
      "Cloud Computing",
      "Git",
      "GitLab",
      "Bash",
      "Unix",
      "SaaS/PaaS/IaaS",
      "Object-Oriented Programming (OOP)",
      "Algorithms",
      "Data Structures",
      "Project Management",
      "React.js",
      "Next.js",
      "Redux.js",
      "Tailwind CSS",
      "SASS",
      "HTML",
      "CSS",
      "Webpack",
      "Figma",
      "WordPress",
      "Shopify",
      "Strapi",
    ],
    projects: [
      {
        name: "BCSolutions · eas'Invoice / eas'eFlow",
        description:
          "Core developer of eas'Invoice / eas'eFlow, an enterprise middleware suite ensuring tax compliance across 60+ countries. Built backend services in Node.js/Express/Nest and React front ends, expanded the microservices architecture, refactored authentication for multi-tenancy and cloud deployment, and co-developed full OpenAPI documentation. Hardened CI/CD with SonarQube and ISO 27001 checks and integrated a RAG chatbot for internal docs, emphasizing test coverage and Agile delivery.",
        link: "https://bcsolutions.fr/en/",
        skills: ["React", "Node.js", "NestJS", "Express", "Kubernetes", "Docker", "PL/SQL"],
      },
      {
        name: "MIRAL · Attraction Parks",
        description:
          "Developed and maintained public websites for Miral attraction parks — Ferrari World and Warner Bros. World Abu Dhabi — as a front-end engineer. Delivered pixel-perfect, responsive React components from designer mockups and collaborated closely with API and CMS teams in a Lerna monorepo spanning multiple property sites.",
        link: "https://miral.ae",
        skills: ["React", "JavaScript", "Node.js"],
      },
      {
        name: "Brava Hotels · Spa & Leisure",
        description:
          "Led end-to-end development of a spa & leisure web platform for Brava Hotels using the MERN stack. Designed the database schema and secure APIs (Node.js/Express), built the responsive React front end, and coordinated a small team (UI designer + junior developer) through launch and production maintenance.",
        link: "https://www.bravahoteles.com/",
        skills: ["React", "Node.js", "Express", "MongoDB"],
      },
      {
        name: "KONFIGEAR · 3D Configurators",
        description:
          "Built immersive 3D product configurators (hats, mirrors, watches) with React, Three.js, and Firebase, letting users customize materials, colors, and shapes in real time. Also designed intuitive admin dashboards for managing product configurations.",
        link: "https://konfigear.com/",
        skills: ["React", "Three.js", "Firebase", "Strapi"],
      },
      {
        name: "LEWINNERSCLUB",
        description:
          "Developed features for LEWINNERSCLUB, a feature-rich web app, over two years — including Stripe subscriptions, an AI marketing-copy tool, and an ebook store — plus a full UI refactor and ongoing deployment and maintenance.",
        link: "https://lewinnersclub.com/en/",
        skills: ["React", "Node.js", "Stripe"],
      },
    ],
    experience: [
      {
        company: "BCSolutions",
        title: "Technical Consultant & Full-Stack Developer",
        dateRange: "April 2023 - Present",
        bullets: [
          "Expanded the microservices architecture by developing new middleware services and designing solutions across the broader system.",
          "Led a major refactor of the authentication system to implement multi-tenancy and prepare the platform for cloud deployment.",
          "Co-developed full API documentation from scratch using OpenAPI and Docusaurus.",
          "Hardened CI/CD pipelines with security checks (ISO 27001) and SonarQube, and optimized Docker and Kubernetes configurations.",
          "Drove AI-augmented development and collaborated on a RAG chatbot to streamline access to internal technical documentation.",
        ],
      },
      {
        company: "Freelance — KONFIGEAR, MIRAL, Le Winners Club, Brava Hotels",
        title: "Freelance Full-Stack Developer",
        dateRange: "May 2020 - April 2023",
        bullets: [
          "Built custom web apps and SaaS platforms for global clients (KONFIGEAR, TM-Consulting, Le Winners Club, Brava Hotels) with React.js, Node.js, MongoDB, and Stripe payments.",
          "Collaborated within engineering teams for clients like MIRAL Group (UAE) to deliver scalable, high-impact application solutions.",
          "Developed and customized Shopify themes and WordPress solutions to meet diverse client needs.",
          "Managed repositories, cloud deployments, and CI/CD pipelines (Azure / GitLab).",
          "Owned client communication, defined technical requirements, hired developers, and met tight deadlines for successful handoffs.",
        ],
      },
    ],
    education: [
      {
        school: "FST Settat",
        degree: "Professional Bachelor's in Application Engineering & Software Development",
        dateRange: "2022 - 2023",
        achievements: [
          "Professional training focused on application design and development.",
        ],
      },
      {
        school: "ENSA Tétouan",
        degree: "Bachelor of Applied Science (BASc), Mechatronics",
        dateRange: "2013 - 2017",
        achievements: [
          "Foundations in applied sciences and mechatronics engineering.",
        ],
      },
    ],
    certifications: [
      {
        name: "EF SET English Certificate C1 Advanced",
        issuer: "EF SET",
        date: "February 2025",
      },
      {
        name: "JavaScript Certification",
        issuer: "CodinGame",
        date: "September 2022",
      },
      {
        name: "MERN Stack Web Development",
        issuer: "3W Academy Maroc",
        date: "April 2022",
        url: "https://3wacademy.fr/",
      },
      {
        name: "Front End Development Libraries",
        issuer: "freeCodeCamp",
        date: "March 2022",
      },
      {
        name: "JavaScript Algorithms and Data Structures",
        issuer: "freeCodeCamp",
        date: "December 2021",
      },
      {
        name: "Responsive Web Design",
        issuer: "freeCodeCamp",
        date: "October 2021",
      },
    ],
    languages: [
      { name: "English", level: "Professional Working" },
      { name: "French", level: "Native or Bilingual" },
      { name: "Arabic", level: "Native or Bilingual" },
    ],
    recommendations: [
      {
        name: "Julien Immelé-Spataro",
        title: "Tech Lead & Freelance Technical Strategist",
        relationship: "Manager · BCSolutions",
        date: "March 2025",
        quote:
          "I had the pleasure of having Amine on my development team at BCSolutions, and I'm delighted to recommend him warmly. He stands out for his exceptional ability to quickly grasp technical and functional contexts, which lets him adapt effectively to diverse projects. His clear, precise communication greatly facilitates collaboration within the team. One of his most remarkable qualities is his commitment to juniors — he never hesitates to help them and adapts to their level to pass on knowledge, creating an inclusive, learning-friendly environment. He also has strong technical foundations and the intellectual curiosity that drives him to go deeper and fully invest in his missions. His proactivity and constant desire to improve make him a valuable asset to any team. I highly recommend Amine for any role requiring advanced technical skills, excellent team spirit, or leadership.",
      },
      {
        name: "Monaim TOUINSSI",
        title: "Senior Azure Cloud & DevOps Engineer",
        relationship: "Manager · BCSolutions",
        date: "February 2025",
        quote:
          "I've had the pleasure of collaborating with Amine on numerous projects, and I can say without hesitation that he is an exceptional professional and a true asset to any team. Amine consistently demonstrates a rare blend of creativity, technical expertise, and strong leadership, making complex projects seem effortless. His proactive approach, meticulous attention to detail, and willingness to go above and beyond have been key factors in the success of our initiatives. What sets Amine apart is not just his skill set but also his genuine commitment to fostering a collaborative environment. He always makes himself available to offer support and insights, ensuring that every team member feels empowered to contribute their best work. His positive attitude and perseverance in the face of challenges inspire those around him to strive for excellence. I wholeheartedly recommend Amine for any opportunity where innovation, teamwork, and dedication are valued.",
      },
      {
        name: "Marouane RAFIK",
        title: "Full-Stack Developer",
        relationship: "Teammate · Eas'Invoice",
        date: "February 2025",
        quote:
          "I recently had the pleasure of collaborating with Amine on the Eas'Invoice project, and was particularly impressed by his professionalism and expertise. He stands out for his mastery of React and Node.js, as well as his ability to solve complex problems with a methodical and effective approach. His team spirit and commitment played a key role in the success of our collaboration. Beyond his technical skills, Amine is a pleasant and approachable person, always listening, ready to share his knowledge and support his team. Working with him was an enriching experience.",
      },
    ],
    ui: {
      hello: "Hello! 👋",
      iAm: "I'm ",
      aboutHeading: "About Me",
      projectsHeading: "Projects",
      experienceHeading: "Experience",
      educationHeading: "Education",
      certificationsHeading: "Certifications",
      languagesHeading: "Languages",
      recommendationsHeading: "Recommendations",
      copyright: "All rights reserved.",
      issued: "Issued",
      contactHeading: "Contact Me",
      contactText: "Let's build something together — feel free to reach out.",
      cv: "CV",
      cvDownload: "Download CV",
      cvHeading: "Curriculum Vitae",
      cvProfile: "Professional Summary",
      cvSkillsHeading: "Skills",
      cvExperience: "Experience",
      cvEducation: "Education",
      cvCertifications: "Certifications",
      cvLanguages: "Languages",
      cvInterests: "Interests",
      cvFrontend: "Frontend",
      cvBackend: "Backend",
      cvDevops: "DevOps",
      cvAiMl: "AI & ML",
      cvPdf: "Download PDF",
      cvBack: "Portfolio",
    },
  },
  fr: {
    name: "Amine Sadali",
    title:       "Consultant Technique Senior & Développeur Full-Stack",
    description:
      "Consultant Technique Senior et Développeur Full-Stack spécialisé en React, Node.js et applications d'entreprise cloud-native intégrant l'IA.",
    social: {
      email: "amine.sadali@gmail.com",
      linkedin: "https://www.linkedin.com/in/aminesadali",
      twitter: "",
      github: "https://github.com/Z4D4LY",
    },
    contact: {
      phone: "0632400390",
      location: "Casablanca",
      nationality: "Marocain",
      remote: "Ouvert au travail à distance & hybride",
    },
    profile:
      "Consultant Technique Senior et Développeur Full-Stack avec plus de 5 ans d'expérience dans la conception et le développement d'applications web évolutives, de microservices et de middlewares d'entreprise. Expertise en React, Node.js, TypeScript, architectures cloud-native et solutions intégrées à l'IA.",
    interests: ["Intelligence Artificielle", "Open Source", "Cloud", "Systèmes d'Information"],
    cvSkills: {
      frontend: [
        "React.js",
        "Next.js",
        "Redux.js",
        "Tailwind CSS",
        "SASS",
        "HTML",
        "CSS",
        "Webpack",
        "Figma",
        "WordPress",
        "Shopify",
        "Strapi",
      ],
      backend: [
        "Node.js",
        "NestJS",
        "Express",
        "Python",
        "TypeScript",
        "JavaScript",
        "Microservices",
        "REST APIs",
        "MERN Stack",
        "Stripe",
        "MongoDB",
        "MySQL",
        "Oracle Database",
        "Microsoft SQL Server",
        "PL/SQL",
        "Firebase",
      ],
      devops: [
        "DevOps",
        "Docker",
        "Kubernetes",
        "CI/CD",
        "SonarQube",
        "Microsoft Azure",
        "Cloud Computing",
        "Git",
        "GitLab",
        "Bash",
        "Unix",
        "SaaS/PaaS/IaaS",
        "Project Management",
      ],
      aiMl: [
        "Agentic AI Development",
        "Retrieval-Augmented Generation (RAG)",
        "Large Language Models (LLM)",
        "Prompt Engineering",
        "LangChain",
      ],
    },
    aboutMe:
      "Conseil, Architecture & Développement d'Applications. Bilan éprouvé à travers des missions en CDI et en freelance, avec la conception et la construction d'applications d'entreprise évolutives. Expertise approfondie dans l'écosystème JavaScript/TypeScript, avec une participation concrète en tant que développeur clé de la suite logicielle intermédiaire eas'eFlow / eas'Invoice. Maîtrise de bout en bout de l'infrastructure DevOps et de l'automatisation. Je livre des solutions performantes intégrées à l'IA pour des clients internationaux, et je suis ouvert aux partenariats stratégiques et aux collaborations techniques.",
    skills: [
      "Agentic AI Development",
      "Retrieval-Augmented Generation (RAG)",
      "Large Language Models (LLM)",
      "Prompt Engineering",
      "LangChain",
      "Node.js",
      "NestJS",
      "Express",
      "Python",
      "TypeScript",
      "JavaScript",
      "Microservices",
      "REST APIs",
      "MERN Stack",
      "Stripe",
      "MongoDB",
      "MySQL",
      "Oracle Database",
      "Microsoft SQL Server",
      "PL/SQL",
      "Firebase",
      "DevOps",
      "Docker",
      "Kubernetes",
      "CI/CD",
      "SonarQube",
      "Microsoft Azure",
      "Cloud Computing",
      "Git",
      "GitLab",
      "Bash",
      "Unix",
      "SaaS/PaaS/IaaS",
      "Object-Oriented Programming (OOP)",
      "Algorithms",
      "Data Structures",
      "Project Management",
      "React.js",
      "Next.js",
      "Redux.js",
      "Tailwind CSS",
      "SASS",
      "HTML",
      "CSS",
      "Webpack",
      "Figma",
      "WordPress",
      "Shopify",
      "Strapi",
    ],
    projects: [
      {
        name: "BCSolutions · eas'Invoice / eas'eFlow",
        description:
          "Développeur clé d'eas'Invoice / eas'eFlow, une suite logicielle intermédiaire d'entreprise assurant la conformité fiscale dans plus de 60 pays. Construire des services backend en Node.js/Express/Nest et des frontends React, étendre l'architecture microservices, refactoriser l'authentification pour le multi-tenant et le cloud, et co-développer une documentation OpenAPI complète. Renforcer la CI/CD avec SonarQube et les contrôles ISO 27001, et intégrer un chatbot RAG pour les documents internes, en misant sur la couverture de tests et la livraison Agile.",
        link: "https://bcsolutions.fr/en/",
        skills: ["React", "Node.js", "NestJS", "Express", "Kubernetes", "Docker", "PL/SQL"],
      },
      {
        name: "MIRAL · Attraction Parks",
        description:
          "Développer et maintenir les sites web publics des parcs d'attractions Miral — Ferrari World et Warner Bros. World Abu Dhabi — en tant qu'ingénieur front-end. Livrer des composants React réactifs et pixel-perfect à partir des maquettes des designers, et collaborer étroitement avec les équipes API et CMS dans un monorepo Lerna couvrant plusieurs sites.",
        link: "https://miral.ae",
        skills: ["React", "JavaScript", "Node.js"],
      },
      {
        name: "Brava Hotels · Spa & Leisure",
        description:
          "Piloter le développement de bout en bout d'une plateforme web spa & loisirs pour Brava Hotels avec la stack MERN. Concevoir le schéma de base de données et des API sécurisées (Node.js/Express), construire le frontend React responsive, et coordonner une petite équipe (designer UI + développeur junior) du lancement à la maintenance en production.",
        link: "https://www.bravahoteles.com/",
        skills: ["React", "Node.js", "Express", "MongoDB"],
      },
      {
        name: "KONFIGEAR · 3D Configurators",
        description:
          "Construire des configurateurs produits 3D immersifs (chapeaux, miroirs, montres) avec React, Three.js et Firebase, permettant aux utilisateurs de personnaliser matériaux, couleurs et formes en temps réel. Concevoir également des tableaux de bord d'administration intuitifs pour gérer les configurations produits.",
        link: "https://konfigear.com/",
        skills: ["React", "Three.js", "Firebase", "Strapi"],
      },
      {
        name: "LEWINNERSCLUB",
        description:
          "Développer des fonctionnalités pour LEWINNERSCLUB, une web app riche, pendant plus de deux ans — abonnements Stripe, un outil de génération de texte marketing par IA, et une librairie numérique — ainsi qu'une refonte complète de l'UI et un déploiement/maintenance continus.",
        link: "https://lewinnersclub.com/en/",
        skills: ["React", "Node.js", "Stripe"],
      },
    ],
    experience: [
      {
        company: "BCSolutions",
        title: "Consultant Technique & Développeur Full-Stack",
        dateRange: "Avril 2023 - Présent",
        bullets: [
          "Étendre l'architecture microservices en développant de nouveaux services pour le middleware et en concevant des solutions pour l'ensemble du système.",
          "Mener un refactor majeur du système d'authentification pour implémenter le multi-tenant et préparer la plateforme au déploiement cloud.",
          "Co-développer une documentation API complète de zéro avec OpenAPI et Docusaurus.",
          "Renforcer les pipelines CI/CD avec des contrôles de sécurité (ISO 27001) et SonarQube, et optimiser les configurations Docker et Kubernetes.",
          "Impulser un développement augmenté par l'IA et collaborer à un chatbot RAG pour fluidifier l'accès à la documentation technique interne.",
        ],
      },
      {
        company: "Freelance — KONFIGEAR, MIRAL, Le Winners Club, Brava Hotels",
        title: "Développeur Full-Stack Freelance",
        dateRange: "Mai 2020 - Avril 2023",
        bullets: [
          "Construire des web apps et plateformes SaaS sur mesure pour des clients internationaux (KONFIGEAR, TM-Consulting, Le Winners Club, Brava Hotels) avec React.js, Node.js, MongoDB et paiements Stripe.",
          "Collaborer au sein d'équipes d'ingénierie pour des clients comme MIRAL Group (EAU) afin de livrer des solutions applicatives évolutives et à fort impact.",
          "Développer et personnaliser des thèmes Shopify et des solutions WordPress selon les besoins variés des clients.",
          "Gérer les dépôts, les déploiements cloud et les pipelines CI/CD (Azure / GitLab).",
          "Prendre en charge la communication client, définir les exigences techniques, recruter des développeurs et respecter des délais serrés pour des livraisons réussies.",
        ],
      },
    ],
    education: [
      {
        school: "FST Settat",
        degree: "Licence Professionnelle en Ingénierie d'Applications et Développement Logiciel",
        dateRange: "2022 - 2023",
        achievements: [
          "Formation professionnelle spécialisée en conception et développement d'applications.",
        ],
      },
      {
        school: "ENSA Tétouan",
        degree: "Cycle d'Ingénieur en Mécatronique",
        dateRange: "2013 - 2017",
        achievements: [
          "Formation d'ingénieur en mécatronique (mécanique, électronique, automatique et informatique).",
        ],
      },
    ],
    certifications: [
      {
        name: "EF SET English Certificate C1 Advanced",
        issuer: "EF SET",
        date: "February 2025",
      },
      {
        name: "JavaScript Certification",
        issuer: "CodinGame",
        date: "September 2022",
      },
      {
        name: "MERN Stack Web Development",
        issuer: "3W Academy Maroc",
        date: "April 2022",
        url: "https://3wacademy.fr/",
      },
      {
        name: "Front End Development Libraries",
        issuer: "freeCodeCamp",
        date: "March 2022",
      },
      {
        name: "JavaScript Algorithms and Data Structures",
        issuer: "freeCodeCamp",
        date: "December 2021",
      },
      {
        name: "Responsive Web Design",
        issuer: "freeCodeCamp",
        date: "October 2021",
      },
    ],
    languages: [
      { name: "Anglais", level: "Professionnel" },
      { name: "Français", level: "Langue maternelle ou bilingue" },
      { name: "Arabe", level: "Langue maternelle ou bilingue" },
    ],
    recommendations: [
      {
        name: "Julien Immelé-Spataro",
        title: "Tech Lead & Stratège technique freelance",
        relationship: "Manager · BCSolutions",
        date: "Mars 2025",
        quote:
          "J'ai eu le plaisir de compter Amine dans mon équipe de développeurs chez BCSolutions, et je suis ravi de pouvoir le recommander chaleureusement. Il se distingue par sa capacité exceptionnelle à comprendre rapidement les contextes techniques et fonctionnels, ce qui lui permet de s'adapter efficacement aux divers projets. Sa communication claire et précise facilite grandement la collaboration au sein de l'équipe. L'une de ses qualités les plus remarquables est son engagement envers les débutants. Il n'hésite jamais à leur apporter son aide et à s'adapter à leur niveau pour transmettre ses connaissances, créant ainsi un environnement de travail inclusif et propice à l'apprentissage. Il possède également une solide culture technique et démontre une curiosité intellectuelle qui le pousse à approfondir les sujets et à s'investir pleinement dans ses missions. Sa proactivité et son désir constant d'amélioration en font un atout précieux pour toute équipe. Je recommande vivement Amine pour tout poste nécessitant des compétences techniques avancées, un excellent esprit d'équipe ou des compétences en encadrement.",
      },
      {
        name: "Monaim TOUINSSI",
        title: "Ingénieur Senior Cloud Azure & DevOps",
        relationship: "Manager · BCSolutions",
        date: "Février 2025",
        quote:
          "J'ai eu le plaisir de collaborer avec Amine sur de nombreux projets, et je peux dire sans hésitation qu'il est un professionnel exceptionnel et un véritable atout pour toute équipe. Amine démontre constamment un mélange rare de créativité, d'expertise technique et de fort leadership, rendant les projets complexes apparents simples. Son approche proactive, son souci méticuleux du détail et sa volonté d'aller au-delà ont été des facteurs clés du succès de nos initiatives. Ce qui distingue Amine, ce n'est pas seulement son savoir-faire mais aussi son réel engagement à favoriser un environnement collaboratif. Il se rend toujours disponible pour offrir son soutien et ses conseils, veillant à ce que chaque membre de l'équipe se sente capable de donner le meilleur de lui-même. Son attitude positive et sa persévérance face aux défis inspirent ceux qui l'entourent à viser l'excellence. Je recommande chaleureusement Amine pour toute opportunité où l'innovation, le travail d'équipe et le dévouement sont valorisés. Sa remarquable capacité à transformer des idées en résultats tangibles en fera sans aucun doute un ajout précieux à toute organisation.",
      },
      {
        name: "Marouane RAFIK",
        title: "Développeur Full-Stack",
        relationship: "Coéquipier · Eas'Invoice",
        date: "Février 2025",
        quote:
          "J'ai récemment eu le plaisir de collaborer avec Amine sur le projet Eas'Invoice, et j'ai été particulièrement impressionné par son professionnalisme et son expertise. Il se démarque par sa maîtrise de React et Node.js, ainsi que par sa capacité à résoudre des problèmes complexes avec une approche méthodique et efficace. Son esprit d'équipe et son engagement ont joué un rôle clé dans la réussite de notre collaboration. Au-delà de ses compétences techniques, Amine est une personne agréable et accessible, toujours à l'écoute, prêt à partager son savoir et à soutenir son équipe. Travailler avec lui a été une expérience enrichissante.",
      },
    ],
    ui: {
      hello: "Bonjour ! 👋",
      iAm: "Je suis ",
      aboutHeading: "À propos",
      projectsHeading: "Projets",
      experienceHeading: "Expérience",
      educationHeading: "Formation",
      certificationsHeading: "Certifications",
      languagesHeading: "Langues",
      recommendationsHeading: "Recommandations",
      copyright: "Tous droits réservés.",
      issued: "Délivré",
      contactHeading: "Contactez-moi",
      contactText:
        "Construisons quelque chose ensemble — n'hésitez pas à me contacter.",
      cv: "CV",
      cvDownload: "Télécharger le CV",
      cvHeading: "Curriculum Vitae",
      cvProfile: "Résumé Professionnel",
      cvSkillsHeading: "Compétences",
      cvExperience: "Expérience",
      cvEducation: "Formation",
      cvCertifications: "Certifications",
      cvLanguages: "Langues",
      cvInterests: "Centres d'intérêt",
      cvFrontend: "Frontend",
      cvBackend: "Backend",
      cvDevops: "DevOps",
      cvAiMl: "IA & ML",
      cvPdf: "Télécharger le PDF",
      cvBack: "Portfolio",
    },
  },
};
